# PostgreSQL. Make sure to install the pg gem.
# gem "pg"

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>  # default PostgreSQL port

development:
  <<: *default
  database: RealRatings_development

test:
  <<: *default
  database: RealRatings_test
production:
  <<: *default
  database: RealRatings_production
  # Uncomment the line below if you want to use the DATABASE_URL environment variable
  # url: <%= ENV['DATABASE_URL'] %>

