# PostgreSQL. Make sure to install the pg gem.
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %> # default to localhost in development
  database: postgres
  username: postgres
  password: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RealRatings_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: RealRatings_test
  username: postgres
  password: postgres

production:
  <<: *default
  host: db
  database: postgres_db
  username: postgres
  password: postgres
